-- =============================================================================
-- Flyway Database Migration: V1 Initial Schema Creation for NipponMaster
-- =============================================================================

-- 1. Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    avatar_url VARCHAR(255),
    jlpt_level VARCHAR(10) DEFAULT 'N5',
    role VARCHAR(20) DEFAULT 'GUEST',
    is_active BOOLEAN DEFAULT TRUE,
    target_level VARCHAR(10),
    onboarding_completed BOOLEAN DEFAULT FALSE
);

-- 2. Vocabularies table
CREATE TABLE IF NOT EXISTS vocabularies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    word VARCHAR(100) NOT NULL,
    reading VARCHAR(100) NOT NULL,
    meaning VARCHAR(500) NOT NULL,
    example_sentence VARCHAR(1000),
    example_meaning VARCHAR(1000),
    jlpt_level VARCHAR(10) NOT NULL,
    word_type VARCHAR(50),
    topic VARCHAR(100)
);

-- 3. Kanjis table
CREATE TABLE IF NOT EXISTS kanjis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    character VARCHAR(10) NOT NULL,
    on_reading VARCHAR(200),
    kun_reading VARCHAR(200),
    meaning VARCHAR(500) NOT NULL,
    stroke_count INTEGER,
    radical VARCHAR(50),
    related_words TEXT,
    jlpt_level VARCHAR(10) NOT NULL
);

-- 4. Grammars table
CREATE TABLE IF NOT EXISTS grammars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    pattern VARCHAR(200) NOT NULL,
    structure VARCHAR(500) NOT NULL,
    meaning TEXT NOT NULL,
    example_sentence TEXT,
    example_meaning TEXT,
    notes TEXT,
    jlpt_level VARCHAR(10) NOT NULL
);

-- 5. Flashcards table (SRS)
CREATE TABLE IF NOT EXISTS flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_type VARCHAR(20) NOT NULL,
    item_id BIGINT NOT NULL,
    easiness_factor DOUBLE PRECISION DEFAULT 2.5,
    interval_days INTEGER DEFAULT 0,
    repetitions INTEGER DEFAULT 0,
    next_review_date TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'NEW'
);

-- 6. Placement Questions table
CREATE TABLE IF NOT EXISTS placement_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    level VARCHAR(10) NOT NULL,
    section VARCHAR(50) NOT NULL,
    question_text TEXT NOT NULL,
    options_json TEXT NOT NULL,
    correct_option INTEGER NOT NULL,
    explanation TEXT,
    display_order INTEGER NOT NULL
);

-- 7. Placement Results table
CREATE TABLE IF NOT EXISTS placement_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_level VARCHAR(10) NOT NULL,
    score INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    score_percent DOUBLE PRECISION NOT NULL,
    recommended_level VARCHAR(10) NOT NULL,
    overall_feedback TEXT,
    section_scores_json TEXT,
    answers_json TEXT
);

-- 8. Subscription Plans table
CREATE TABLE IF NOT EXISTS subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    price BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL,
    duration_days INTEGER NOT NULL,
    plan_type VARCHAR(50) NOT NULL,
    jlpt_level VARCHAR(10),
    features VARCHAR(2000),
    badge VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE
);

-- 9. Subscriptions table
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id BIGINT NOT NULL REFERENCES subscription_plans(id),
    status VARCHAR(20) NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    payment_id VARCHAR(255),
    payment_provider VARCHAR(50),
    amount BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL
);

-- 10. Classrooms table
CREATE TABLE IF NOT EXISTS classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    join_code VARCHAR(50) NOT NULL UNIQUE,
    teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    level VARCHAR(10) NOT NULL,
    max_students INTEGER DEFAULT 50,
    is_active BOOLEAN DEFAULT TRUE
);

-- 11. Classroom Students table
CREATE TABLE IF NOT EXISTS classroom_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_classroom_student UNIQUE (classroom_id, student_id)
);
