-- =============================================================================
-- Flyway Database Migration: V2 Add Exams and Questions Tables
-- =============================================================================

CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    title VARCHAR(300) NOT NULL,
    description TEXT,
    jlpt_level VARCHAR(10) NOT NULL,
    exam_type VARCHAR(20) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    total_score INTEGER,
    is_published BOOLEAN DEFAULT FALSE,
    is_shuffle_questions BOOLEAN DEFAULT FALSE,
    is_shuffle_options BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    content TEXT NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_answer VARCHAR(1) NOT NULL,
    explanation TEXT,
    score INTEGER DEFAULT 1,
    order_index INTEGER,
    exam_id BIGINT NOT NULL REFERENCES exams(id) ON DELETE CASCADE
);

-- Ensure columns exist if table was previously auto-created by Hibernate without them
ALTER TABLE exams ADD COLUMN IF NOT EXISTS is_shuffle_questions BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS is_shuffle_options BOOLEAN DEFAULT FALSE;
